/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vs.time.kkv.connector;

import java.awt.Point;
import vs.time.kkv.models.VS_SETTING;

/**
 *
 * @author kyo
 */
public class WLANSetting extends javax.swing.JFrame {

  MainForm mainForm = null;
  int PORT_LISTING_INT = 8888;
  int PORT_SENDING_INT = 8889;
  
  /**
   * Creates new form WLANSetting
   */
  public WLANSetting(MainForm mainForm) {
    initComponents();
    this.mainForm = mainForm;
    setVisible(false);
  }
   
  static WLANSetting singelton  = null;
  public static WLANSetting init(MainForm mainForm){
    if (singelton==null){
      singelton = new WLANSetting(mainForm);
    }
    
    singelton.PORT_LISTING_INT = VS_SETTING.getParam(mainForm.con, "PORT_LISTING_INT", singelton.PORT_LISTING_INT);
    singelton.PORT_SENDING_INT= VS_SETTING.getParam(mainForm.con, "PORT_SENDING_INT", singelton.PORT_SENDING_INT);
    
    
    singelton.PORT_FOR_LISTING.setText(""+singelton.PORT_LISTING_INT);
    singelton.PORT_FOR_SENDING.setText(""+singelton.PORT_SENDING_INT);
    
    WLANSetting th = singelton;
    Point p = mainForm.getLocationOnScreen();
    th.setLocation(p.x + mainForm.getWidth() / 2 - th.getSize().width / 2, p.y + mainForm.getHeight() / 2 - th.getSize().height / 2);
    th.setAlwaysOnTop(true);
    th.setResizable(false);       
    
    return singelton;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    PORT_FOR_LISTING = new javax.swing.JTextField();
    PORT_FOR_SENDING = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jButOk = new javax.swing.JButton();
    jButCancel = new javax.swing.JButton();

    setTitle("WLan Setting");
    setResizable(false);

    jLabel1.setText("Listining Port");

    jLabel2.setText("Control Port");

    PORT_FOR_LISTING.setText("8888");

    PORT_FOR_SENDING.setText("8889");

    jButOk.setText("Ok");
    jButOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButOkActionPerformed(evt);
      }
    });

    jButCancel.setText("Cancel");
    jButCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButCancelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButOk, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        .addGap(18, 28, Short.MAX_VALUE)
        .addComponent(jButCancel)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButOk)
          .addComponent(jButCancel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(PORT_FOR_LISTING)
          .addComponent(PORT_FOR_SENDING))
        .addContainerGap())
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(PORT_FOR_LISTING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(PORT_FOR_SENDING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelActionPerformed
    setVisible(false);
  }//GEN-LAST:event_jButCancelActionPerformed

  private void jButOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOkActionPerformed
    try{
      PORT_LISTING_INT = Integer.parseInt(PORT_FOR_LISTING.getText());
    }catch(Exception e){}
    try{
      PORT_SENDING_INT = Integer.parseInt(PORT_FOR_SENDING.getText());
    }catch(Exception e){}
    
    VS_SETTING.setParam(mainForm.con, "PORT_LISTING_INT", ""+singelton.PORT_LISTING_INT);
    VS_SETTING.setParam(mainForm.con, "PORT_SENDING_INT", ""+singelton.PORT_SENDING_INT);
    
    
    setVisible(false);
  }//GEN-LAST:event_jButOkActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField PORT_FOR_LISTING;
  private javax.swing.JTextField PORT_FOR_SENDING;
  private javax.swing.JButton jButCancel;
  private javax.swing.JButton jButOk;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
