/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vs.time.kkv.connector.MainlPannels.RegistrationListImport;

import vs.time.kkv.connector.web.RaceHttpServer;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import vs.time.kkv.connector.MainForm;
import vs.time.kkv.connector.MainlPannels.RegistrationListImport.RegistrationSites.FPVSport;
import vs.time.kkv.connector.MainlPannels.RegistrationListImport.RegistrationSites.IRegSite;
import vs.time.kkv.connector.MainlPannels.RegistrationTab;
import vs.time.kkv.connector.Utils.TTS.TextToSpeachFactory;
import vs.time.kkv.models.VS_RACE;
import vs.time.kkv.models.VS_REGISTRATION;
import vs.time.kkv.models.VS_SETTING;

/**
 *
 * @author kyo
 */
public class RegistrationImportForm extends javax.swing.JFrame {

  RegistrationTab regTab = null;

  List<IRegSite> sites = new ArrayList<>();

  public IRegSite getSite(String name) {
    for (IRegSite site : sites) {
      if (site.getSystemName().equalsIgnoreCase(name)) {
        return site;
      }
    }
    return null;
  }

  public final String PLEASE_SELECT_WEB_SYSTEM = "none";

  /**
   * Creates new form WLANSetting
   */
  public RegistrationImportForm(RegistrationTab regTab) {
    initComponents();
    this.regTab = regTab;
    setVisible(false);

    sites.add(new FPVSport());

    String[] list = new String[sites.size() + 1];
    list[0] = PLEASE_SELECT_WEB_SYSTEM;
    int index = 1;
    for (IRegSite site : sites) {
      list[index] = site.getSystemName();
      index++;
    }
    jcbSites.setModel(new javax.swing.DefaultComboBoxModel(list));
  }

  static RegistrationImportForm singelton = null;

  public static RegistrationImportForm init(RegistrationTab regTab) {
    if (singelton == null) {
      singelton = new RegistrationImportForm(regTab);
    }

    RegistrationImportForm th = singelton;
    if (regTab != null) {
      regTab.mainForm.setFormOnCenter(th);
    }

    return singelton;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButOk = new javax.swing.JButton();
    jButCancel = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jcbSites = new javax.swing.JComboBox<>();
    jcbRaces = new javax.swing.JComboBox<>();

    setTitle("Pilots Import from Web");
    setIconImage(MainForm.getWindowsIcon().getImage());
    setResizable(false);

    jButOk.setText("Ok");
    jButOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButOkActionPerformed(evt);
      }
    });

    jButCancel.setText("Cancel");
    jButCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButCancelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
        .addComponent(jButCancel)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButOk)
          .addComponent(jButCancel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel3.setText("Web Resource");

    jLabel4.setText("Race");

    jcbSites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jcbSites.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jcbSitesPropertyChange(evt);
      }
    });

    jcbRaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jcbSites, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jcbRaces, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jcbSites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jcbRaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelActionPerformed
    setVisible(false);
  }//GEN-LAST:event_jButCancelActionPerformed

  private void jButOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOkActionPerformed
    if (PLEASE_SELECT_WEB_SYSTEM.equalsIgnoreCase(jcbSites.getSelectedItem().toString())) {
    } else {
      try {
        IRegSite site = getSite(jcbSites.getSelectedItem().toString());
        if (site != null) {
          site.load();
          List<VS_RACE> races = site.getRaces();
          int count_export_pilots = 0;
          for (VS_RACE race : races) {
            if (race.RACE_NAME.equalsIgnoreCase(jcbRaces.getSelectedItem().toString())) {              
              if (race.users != null) {                
                for (VS_REGISTRATION pilot : race.users) {

                }
              }              
              break;
            }
          }
          JOptionPane.showMessageDialog(this, "Count export pilots : " + count_export_pilots, "Information", JOptionPane.INFORMATION_MESSAGE);      
        }
      } catch (Exception e) {
        MainForm._toLog(e);
      }
    }
    setVisible(false);
  }//GEN-LAST:event_jButOkActionPerformed

  private void jcbSitesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcbSitesPropertyChange
    jcbRaces.setModel(new javax.swing.DefaultComboBoxModel(new String[0]));
    if (PLEASE_SELECT_WEB_SYSTEM.equalsIgnoreCase(jcbSites.getSelectedItem().toString())) {
    } else {
      try {
        IRegSite site = getSite(jcbSites.getSelectedItem().toString());
        if (site != null) {
          site.load();
          List<VS_RACE> races = site.getRaces();
          String[] list = new String[races.size()];
          int index = 0;
          for (VS_RACE race : races) {
            list[index] = race.RACE_NAME;
            index++;
          }
          jcbRaces.setModel(new javax.swing.DefaultComboBoxModel(list));
        }
      } catch (Exception e) {
        MainForm._toLog(e);
      }
    }
  }//GEN-LAST:event_jcbSitesPropertyChange

  public void buttnCaptionRefresh() {

  }

  public static void runWebServer(MainForm mainForm) {
    mainForm.httpServer = new RaceHttpServer(mainForm, VS_SETTING.getParam(mainForm.con, "WEB_PORT", 80));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButCancel;
  private javax.swing.JButton jButOk;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JComboBox<String> jcbRaces;
  private javax.swing.JComboBox<String> jcbSites;
  // End of variables declaration//GEN-END:variables
}
