/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vs.time.kkv.connector.MainlPannels;

import vs.time.kkv.connector.Users.*;
import KKV.DBControlSqlLite.DBModelTest;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;
import javax.swing.JPopupMenu;
import javax.swing.JSpinner;
import vs.time.kkv.connector.MainForm;
import vs.time.kkv.connector.Race.RaceList;
import vs.time.kkv.connector.Utils.KKVTreeTable.ListEditTools;
import vs.time.kkv.models.VS_RACE;
import vs.time.kkv.models.VS_REGISTRATION;
import vs.time.kkv.models.VS_STAGE;
import vs.time.kkv.models.VS_USERS;

/**
 *
 * @author kyo
 */
public class RegisterPilotlForm extends javax.swing.JFrame {

  MainForm mainForm = null;
  long reg_Id = -1;
  VS_REGISTRATION usr = null;
  

  /**
   * Creates new form UserControlForm
   */
  private RegisterPilotlForm(MainForm mainForm) {
    initComponents();
    this.mainForm = mainForm;        
  }

  private static RegisterPilotlForm form = null;

  public static RegisterPilotlForm init(MainForm mainForm, long reg_Id) {
    if (form == null) {
      form = new RegisterPilotlForm(mainForm);
      if (mainForm != null) {
        mainForm.setFormOnCenter(form);
      }
    }
    form.reg_Id = reg_Id;
    form.setVisible(false);
    form.prepareForm();

    return form;
  }

  public void prepareForm() {

    if (reg_Id != -1) {
      try {
        usr = VS_REGISTRATION.dbControl.getItem(mainForm.con, "ID=?",reg_Id);        
        edUser.setText(usr.VS_USER_NAME);
        chEnabledSound.setSelected(usr.VS_SOUND_EFFECT==1);                
      } catch (Exception e) {
        mainForm.error_log.writeFile(e);
        JOptionPane.showMessageDialog(this, "Loading user is error. " + getName().toString(), "Error", JOptionPane.ERROR_MESSAGE);
      }
    }else{
       usr = new VS_REGISTRATION();
    }

    if (reg_Id != -1) {
      edTransponder.setText("" + usr.VS_TRANSPONDER);
      jcbPilotType.setSelectedIndex(usr.PILOT_TYPE);
    } else {
      edTransponder.setText("");
      edUser.setText("");
      chEnabledSound.setSelected(true);
    }      
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    edTransponder = new javax.swing.JTextField();
    edUser = new javax.swing.JTextField();
    chEnabledSound = new javax.swing.JCheckBox();
    jButton1 = new javax.swing.JButton();
    butPilots = new javax.swing.JButton();
    butUsedLastTransponderID = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jcbPilotType = new javax.swing.JComboBox();
    jPanel2 = new javax.swing.JPanel();
    bSave = new javax.swing.JButton();
    bCancel = new javax.swing.JButton();

    setTitle("Pilot Card");
    setResizable(false);

    jLabel1.setText("Transponder ID:");

    jLabel2.setText("Pilot name:");

    edTransponder.setText("0000");

    chEnabledSound.setText("sound");
    chEnabledSound.setToolTipText("");
    chEnabledSound.setAutoscrolls(true);

    jButton1.setText("Speek Name");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    butPilots.setText("...");
    butPilots.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        butPilotsActionPerformed(evt);
      }
    });

    butUsedLastTransponderID.setText("Last Transpnder");
    butUsedLastTransponderID.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        butUsedLastTransponderIDActionPerformed(evt);
      }
    });

    jLabel3.setText("Pilot type:");

    jcbPilotType.setModel(new javax.swing.DefaultComboBoxModel(MainForm.PILOT_TYPES));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jLabel2)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(edTransponder, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
            .addComponent(butUsedLastTransponderID))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jcbPilotType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(edUser))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(butPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(chEnabledSound, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(edTransponder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(butUsedLastTransponderID))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(edUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(butPilots))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jcbPilotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(chEnabledSound)))
    );

    bSave.setText("Save");
    bSave.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bSaveActionPerformed(evt);
      }
    });

    bCancel.setText("Cancel");
    bCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCancelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(bSave)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(bCancel)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(17, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bSave)
          .addComponent(bCancel))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
    setVisible(false);
  }//GEN-LAST:event_bCancelActionPerformed

  private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
    try {      
      // Check for constarin
      VS_REGISTRATION check = null;
      VS_REGISTRATION check2 = null;
      if (usr==null) usr = new VS_REGISTRATION();
      usr.VS_TRANSPONDER = Integer.parseInt(edTransponder.getText());
      usr.VS_RACE_ID = mainForm.activeRace.RACE_ID;
      usr.IS_ACTIVE = 1;
      usr.VS_USER_NAME = edUser.getText();
      usr.VS_SOUND_EFFECT = chEnabledSound.isSelected()?1:0;
      usr.PILOT_TYPE = jcbPilotType.getSelectedIndex();
      if (usr.ID!=-1) {        
        
        check = VS_REGISTRATION.dbControl.getItem(mainForm.con, "VS_RACE_ID=? and VS_TRANSPONDER=? and ID<>?", usr.VS_RACE_ID, usr.VS_TRANSPONDER,usr.ID);
        check2 = VS_REGISTRATION.dbControl.getItem(mainForm.con, "VS_RACE_ID=? and VS_USER_NAME=? and ID<>?", usr.VS_RACE_ID, usr.VS_USER_NAME,usr.ID);
        if (check2!=null) {
          int res = JOptionPane.showConfirmDialog(this, "Pilot '"+usr.VS_USER_NAME+"' has been registred.\nPlease change the pilot name?", "Pilot has been registred.", JOptionPane.CLOSED_OPTION);
          return; 
        }
        if (check!=null){
          int res = JOptionPane.showConfirmDialog(this, "Transponder '"+usr.VS_TRANSPONDER+"' has been registred.\nPlease change the transponder ID?", "Transponder has been registred.", JOptionPane.CLOSED_OPTION);
          return;          
        }                
        VS_REGISTRATION.dbControl.update(mainForm.con,usr);        
        
        /*// add user to all stages
        for (int s_idx=0; s_idx<mainForm.getTabbedPanels().getComponentCount(); s_idx++){
                  
        }*/
        
      } else {      
        usr.NUM = VS_REGISTRATION.maxNum(mainForm.con, usr.VS_RACE_ID)+1;      
        check = VS_REGISTRATION.dbControl.getItem(mainForm.con, "VS_RACE_ID=? and VS_TRANSPONDER=?", usr.VS_RACE_ID, usr.VS_TRANSPONDER);
        check2 = VS_REGISTRATION.dbControl.getItem(mainForm.con, "VS_RACE_ID=? and VS_USER_NAME=?", usr.VS_RACE_ID, usr.VS_USER_NAME);
        
        if (check2!=null) {
          int res = JOptionPane.showConfirmDialog(this, "Pilot '"+usr.VS_USER_NAME+"' has been registred.\nPlease change the pilot name?", "Pilot has been registred.", JOptionPane.CLOSED_OPTION);
          return; 
        }
        
        if (check!=null){
          int res = JOptionPane.showConfirmDialog(this, "Transponder is registred.\nDo you want to rewrite?", "Transponder is registred.", JOptionPane.YES_NO_OPTION);
          if (res==JOptionPane.YES_OPTION){
            usr.ID = check.ID;
            usr.NUM = check.NUM;            
            VS_REGISTRATION.dbControl.update(mainForm.con,usr);
          }else{
            return;
          }      
        }else{        
          VS_REGISTRATION.dbControl.insert(mainForm.con, usr);
        } 
      }  
      setVisible(false);
      if (mainForm!=null && mainForm.regForm!=null){        
        mainForm.regForm.refreshData();
      }
    } catch (Exception e) {  
      mainForm.error_log.writeFile(e);
    }  
  }//GEN-LAST:event_bSaveActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    mainForm.speaker.speak(mainForm.speaker.getSpeachMessages().msg(edUser.getText()));
  }//GEN-LAST:event_jButton1ActionPerformed

  private void butPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPilotsActionPerformed
    //UserList.init(mainForm).setVisible(true);
    UserList.init(mainForm,new UserList.UserListListener() {
      @Override
      public boolean selectUserAndCloseWindow(VS_USERS user) {
        if (user!=null){
          edUser.setText(user.VS_NAME);
          edTransponder.setText(""+user.VSID);
        }
        return true;
      }
    }).setVisible(true);
  }//GEN-LAST:event_butPilotsActionPerformed

  private void butUsedLastTransponderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUsedLastTransponderIDActionPerformed
    // TODO add your handling code here:
    if (mainForm.lastTranponderID!=-1){
      edTransponder.setText(""+mainForm.lastTranponderID);
    }
  }//GEN-LAST:event_butUsedLastTransponderIDActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RegisterPilotlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RegisterPilotlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RegisterPilotlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RegisterPilotlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RegisterPilotlForm(null).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bCancel;
  private javax.swing.JButton bSave;
  private javax.swing.JButton butPilots;
  private javax.swing.JButton butUsedLastTransponderID;
  private javax.swing.JCheckBox chEnabledSound;
  public javax.swing.JTextField edTransponder;
  private javax.swing.JTextField edUser;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JComboBox jcbPilotType;
  // End of variables declaration//GEN-END:variables
}
