/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vs.time.kkv.connector.MainlPannels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import vs.time.kkv.connector.MainForm;
import vs.time.kkv.connector.Race.RaceList;
import vs.time.kkv.connector.Utils.KKVTreeTable.ListEditTools;
import vs.time.kkv.models.VS_RACE;
import vs.time.kkv.models.VS_REGISTRATION;

/**
 *
 * @author kyo
 */
public class RegistrationTab extends javax.swing.JPanel {

  MainForm mainForm;
  RegistrationModelTable regModelTable = null;
  JPopupMenu popup = null;
  
  
  /**
   * Creates new form RegistrationForm
   */
  public RegistrationTab(MainForm _mainForm) {
    initComponents();
    this.mainForm = _mainForm;
    regModelTable = new RegistrationModelTable(this);
    jtPilotRegistration.setModel(regModelTable);
    jtPilotRegistration.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    jtPilotRegistration.getColumnModel().getColumn(4).setPreferredWidth(800);
    jtPilotRegistration.setRowHeight(28);
    jtPilotRegistration.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(ListEditTools.generateBox(mainForm.PILOT_TYPES)));
    
    popup = new JPopupMenu();
    JMenuItem miEdit = new JMenuItem("Edit");
    popup.add(miEdit);
    JMenuItem miAdd = new JMenuItem("Add");
    popup.add(miAdd);
    JMenuItem miDelete = new JMenuItem("Delete");
    popup.add(miDelete);
    miEdit.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        int row = jtPilotRegistration.getSelectedRow();
        VS_REGISTRATION regInfo = regModelTable.getRegInfo(row);
        if (regInfo!=null){
          RegisterPilotlForm.init(mainForm, regInfo.ID).setVisible(true);
        }  
      }
    });
    miAdd.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        butRegistPilotActionPerformed(e);
      }
    });
    miDelete.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        int row = jtPilotRegistration.getSelectedRow();
        VS_REGISTRATION regInfo = regModelTable.getRegInfo(row);
        if (regInfo != null) {
          int res = JOptionPane.showConfirmDialog(RegistrationTab.this, "Do you want to delete '"+regInfo.VS_USER_NAME+"' Pilot?", "Delete Pilot", JOptionPane.YES_NO_OPTION);
          if (res == JOptionPane.YES_OPTION) {
            try {
              regInfo.dbControl.delete(mainForm.con, regInfo);
              RegistrationTab.this.refreshData();
            } catch (Exception ex) {
              mainForm.error_log.writeFile(ex);
            }
          }
        }
      }
    });
    jtPilotRegistration.add(popup);
    
    jtPilotRegistration.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
      }

      public void mouseReleased(MouseEvent e) {
        if (e.isPopupTrigger()) {
          JTable source = (JTable) e.getSource();
          int row = source.rowAtPoint(e.getPoint());
          int column = source.columnAtPoint(e.getPoint());
          if (!source.isRowSelected(row)) {
            source.changeSelection(row, column, false, false);
          }
          popup.show(e.getComponent(), e.getX(), e.getY());
        }
      }

    });
    
    refreshData();
  }
  
  public void refreshData(){
    regModelTable.loadData();
    jtPilotRegistration.addNotify();     
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    butRegistPilot = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jtPilotRegistration = new javax.swing.JTable();

    butRegistPilot.setText("Register Pilot");
    butRegistPilot.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        butRegistPilotActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(butRegistPilot)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(butRegistPilot)
        .addContainerGap(13, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    jtPilotRegistration.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jtPilotRegistration);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void butRegistPilotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistPilotActionPerformed
    // TODO add your handling code here:
    RegisterPilotlForm.init(mainForm, -1).setVisible(true);
  }//GEN-LAST:event_butRegistPilotActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton butRegistPilot;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jtPilotRegistration;
  // End of variables declaration//GEN-END:variables
}
