/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vs.time.kkv.connector.MainlPannels.stage;

import vs.time.kkv.connector.Race.*;
import vs.time.kkv.connector.Users.*;
import KKV.DBControlSqlLite.DBModelTest;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;
import vs.time.kkv.connector.MainForm;
import vs.time.kkv.models.VS_STAGE;
import vs.time.kkv.models.VS_RACE;
import vs.time.kkv.models.VS_SETTING;
import vs.time.kkv.models.VS_USERS;

/**
 *
 * @author kyo
 */
public class StageNewForm extends javax.swing.JFrame {

  MainForm mainForm = null;
  int tabID = -1;
  VS_STAGE stage = null;
  //VS_RACE race = null;

  /**
   * Creates new form UserControlForm
   */
  private StageNewForm(MainForm mainForm) {
    this.mainForm = mainForm;
    initComponents();
    channelControls.add(new ChannelControl(1, jlChannel1, jcbChannel1));
    channelControls.add(new ChannelControl(2, jlChannel2, jcbChannel2));
    channelControls.add(new ChannelControl(3, jlChannel3, jcbChannel3));
    channelControls.add(new ChannelControl(4, jlChannel4, jcbChannel4));
    channelControls.add(new ChannelControl(5, jlChannel5, jcbChannel5));
    channelControls.add(new ChannelControl(6, jlChannel6, jcbChannel6));
    channelControls.add(new ChannelControl(7, jlChannel7, jcbChannel7));
    channelControls.add(new ChannelControl(8, jlChannel8, jcbChannel8));
  }

  private static StageNewForm form = null;

  public static StageNewForm init(MainForm mainForm, VS_STAGE stage) {
    if (form == null) {
      form = new StageNewForm(mainForm);
      if (mainForm != null) {
        mainForm.setFormOnCenter(form);
      }
    }
    form.setVisible(false);
    form.stage = stage;
    form.prepareForm();

    return form;
  }

  class ChannelControl {

    int index;
    JLabel label;
    JComboBox box;

    public ChannelControl(int index, JLabel label, JComboBox box) {
      this.index = index;
      this.label = label;
      this.box = box;
    }
  }
  List<ChannelControl> channelControls = new ArrayList<ChannelControl>();

  public void prepareForm() {

    List<VS_STAGE> stages = null;
    try {
      stages = VS_STAGE.dbControl.getList(mainForm.con, "RACE_ID=? order by ID", mainForm.activeRace.RACE_ID);
    } catch (Exception e) {
    }
    if (stages == null) {
      stages = new ArrayList<VS_STAGE>();
    }
    String[] stages_st = new String[stages.size() + 1];
    String last_stage = "";
    for (int i = 0; i < stages_st.length; i++) {
      if (i == 0) {
        stages_st[i] = "auto";
      } else {
        stages_st[i] = stages.get(i - 1).CAPTION;
        last_stage = stages_st[i];
      }
    }
    parentStage.setModel(new javax.swing.DefaultComboBoxModel(stages_st));        

    if (stage != null) {
      butRecrateGropus.setVisible(true);
      jtCaption.setText(stage.CAPTION);
      jchGroupByPilotType.setSelected(stage.FLAG_BY_PYLOT_TYPE == 1);
      jtLapsCount.setText("" + stage.LAPS);
      jtMinLapTime.setText("" + stage.MIN_LAP_TIME);
      jtCountOfPilots.setSelectedIndex(stage.COUNT_PILOTS_IN_GROUP - 1);
      String[] channels = stage.CHANNELS.split(";");
      int index = 0;
      for (String channel : channels) {
        channelControls.get(index).box.setSelectedItem(channel);
        index++;
      }
      jcbStageType.setSelectedIndex(stage.STAGE_TYPE);
      try{
        parentStage.setSelectedItem(stage.PARENT_STAGE);
      }catch(Exception e){}
    } else {
      parentStage.setSelectedItem(last_stage);
      butRecrateGropus.setVisible(false);
      String st_channels = VS_SETTING.getParam(mainForm.con, "CHANNELS", "R2;R5;R7");
      String[] channels = st_channels.split(";");
      int index = 0;
      for (String channel : channels) {
        channelControls.get(index).box.setSelectedItem(channel);
        index++;
      }
      jtCountOfPilots.setSelectedIndex(channels.length - 1);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    Caption = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jtCaption = new javax.swing.JTextField();
    jtLapsCount = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jtMinLapTime = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jlChannel1 = new javax.swing.JLabel();
    jcbChannel1 = new javax.swing.JComboBox();
    jlChannel2 = new javax.swing.JLabel();
    jcbChannel2 = new javax.swing.JComboBox();
    jlChannel3 = new javax.swing.JLabel();
    jcbChannel3 = new javax.swing.JComboBox();
    jlChannel4 = new javax.swing.JLabel();
    jcbChannel4 = new javax.swing.JComboBox();
    jlChannel5 = new javax.swing.JLabel();
    jcbChannel5 = new javax.swing.JComboBox();
    jlChannel6 = new javax.swing.JLabel();
    jcbChannel6 = new javax.swing.JComboBox();
    jlChannel7 = new javax.swing.JLabel();
    jcbChannel7 = new javax.swing.JComboBox();
    jlChannel8 = new javax.swing.JLabel();
    jcbChannel8 = new javax.swing.JComboBox();
    jchGroupByPilotType = new javax.swing.JCheckBox();
    jLabel4 = new javax.swing.JLabel();
    jcbStageType = new javax.swing.JComboBox();
    jtCountOfPilots = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    parentStage = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    bSave = new javax.swing.JButton();
    bCancel = new javax.swing.JButton();
    butRecrateGropus = new javax.swing.JButton();

    setTitle("Add Stage");
    setResizable(false);

    Caption.setText("Stage name:");

    jLabel2.setText("Laps:");

    jLabel3.setText("Min lap time (sec):");

    jtMinLapTime.setText("18");

    jLabel1.setText("Count of pilots in group:");

    jlChannel1.setText("Channel 1:");

    jcbChannel1.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel2.setText("Channel 2:");

    jcbChannel2.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel3.setText("Channel 3:");

    jcbChannel3.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel4.setText("Channel 4:");

    jcbChannel4.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel5.setText("Channel 5:");

    jcbChannel5.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel6.setText("Channel 6:");

    jcbChannel6.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel7.setText("Channel 7:");

    jcbChannel7.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jlChannel8.setText("Channel 8:");

    jcbChannel8.setModel(new javax.swing.DefaultComboBoxModel(mainForm.getBands()));

    jchGroupByPilotType.setText("Create groups by pilot type");
    jchGroupByPilotType.setAlignmentY(0.0F);
    jchGroupByPilotType.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jchGroupByPilotType.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jchGroupByPilotType.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jchGroupByPilotTypeActionPerformed(evt);
      }
    });

    jLabel4.setText("Stage type:");

    jcbStageType.setModel(new javax.swing.DefaultComboBoxModel(MainForm.STAGE_TYPES));
    jcbStageType.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcbStageTypeActionPerformed(evt);
      }
    });
    jcbStageType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jcbStageTypePropertyChange(evt);
      }
    });

    jtCountOfPilots.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
    jtCountOfPilots.setSelectedIndex(2);
    jtCountOfPilots.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jtCountOfPilotsPropertyChange(evt);
      }
    });

    jLabel5.setText("Copy groups from stage");

    parentStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jchGroupByPilotType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(Caption)
              .addComponent(jLabel4))
            .addGap(75, 75, 75)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jcbStageType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jtCaption)))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2)
                  .addComponent(jLabel3)
                  .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jtLapsCount)
                  .addComponent(jtCountOfPilots, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jtMinLapTime)))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addGap(269, 269, 269))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlChannel1)
                    .addComponent(jlChannel2)
                    .addComponent(jlChannel3)
                    .addComponent(jlChannel4))
                  .addGap(20, 20, 20)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbChannel2, 0, 44, Short.MAX_VALUE)
                    .addComponent(jcbChannel3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbChannel4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbChannel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(43, 43, 43)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addComponent(jlChannel5)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(jcbChannel5, 0, 44, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addComponent(jlChannel6)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(jcbChannel6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addComponent(jlChannel7)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(jcbChannel7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addComponent(jlChannel8)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(jcbChannel8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(parentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jcbStageType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Caption)
          .addComponent(jtCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jchGroupByPilotType)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(parentStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jtLapsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jtMinLapTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jtCountOfPilots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlChannel1)
          .addComponent(jcbChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jlChannel5)
          .addComponent(jcbChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlChannel2)
          .addComponent(jcbChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jlChannel6)
          .addComponent(jcbChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlChannel3)
          .addComponent(jcbChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jlChannel7)
          .addComponent(jcbChannel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlChannel4)
          .addComponent(jcbChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jlChannel8)
          .addComponent(jcbChannel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(106, Short.MAX_VALUE))
    );

    bSave.setText("Save");
    bSave.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bSaveActionPerformed(evt);
      }
    });

    bCancel.setText("Cancel");
    bCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCancelActionPerformed(evt);
      }
    });

    butRecrateGropus.setText("Save & Recreate Groups");
    butRecrateGropus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        butRecrateGropusActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(bSave)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(butRecrateGropus)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(bCancel)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bSave)
          .addComponent(bCancel)
          .addComponent(butRecrateGropus))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
    setVisible(false);
  }//GEN-LAST:event_bCancelActionPerformed

  private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
    try {
      if (stage == null) {
        stage = new VS_STAGE();
        stage.IS_GROUP_CREATED = 0;
        stage.RACE_ID = mainForm.activeRace.RACE_ID;
        stage.STAGE_NUM = 1;
        try {
          int max = (int) VS_STAGE.dbControl.getMax(mainForm.con, "STAGE_NUM", "RACE_ID=?", stage.RACE_ID);
          stage.STAGE_NUM = max + 1;
        } catch (Exception e) {
        }
      }
      stage.PARENT_STAGE = parentStage.getSelectedItem().toString();
      stage.CAPTION = jtCaption.getText();
      stage.FLAG_BY_PYLOT_TYPE = jchGroupByPilotType.isSelected() ? 1 : 0;
      try {
        stage.LAPS = Integer.parseInt(jtLapsCount.getText());
      } catch (Exception e) {
      }
      try {
        stage.MIN_LAP_TIME = Integer.parseInt(jtMinLapTime.getText());
      } catch (Exception e) {
      }
      int count_of_pilots = jtCountOfPilots.getSelectedIndex() + 1;
      stage.COUNT_PILOTS_IN_GROUP = count_of_pilots;
      stage.STAGE_TYPE = jcbStageType.getSelectedIndex();
      String channels = "";
      for (int index = 0; index < count_of_pilots; index++) {
        channels += channelControls.get(index).box.getSelectedItem().toString() + ";";
      }
      stage.CHANNELS = channels;
      stage.resetSelectedTab(mainForm.con, stage.RACE_ID);
      stage.IS_SELECTED = 1;
      if (stage.ID == -1) {
        stage.dbControl.insert(mainForm.con, stage);
      } else {
        stage.dbControl.update(mainForm.con, stage);
      }
      setVisible(false);
      mainForm.setActiveRace(mainForm.activeRace);
      VS_SETTING.setParam(mainForm.con, "CHANNELS", channels);
    } catch (Exception e) {
      mainForm.error_log.writeFile(e);
      JOptionPane.showMessageDialog(this, "Saving race is error. " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_bSaveActionPerformed

  private void jchGroupByPilotTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchGroupByPilotTypeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jchGroupByPilotTypeActionPerformed

  private void jcbStageTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcbStageTypePropertyChange
    // TODO add your handling code here:
    if (stage == null) {
      String text = jcbStageType.getSelectedItem().toString();
      int max = 1;
      try {
        max = (int) VS_STAGE.dbControl.getMax(mainForm.con, "STAGE_NUM", "RACE_ID=?", mainForm.activeRace.RACE_ID) + 1;
      } catch (Exception e) {
      }
      jtCaption.setText(text + max);
    }
  }//GEN-LAST:event_jcbStageTypePropertyChange

  private void jtCountOfPilotsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtCountOfPilotsPropertyChange
    // TODO add your handling code here:    
    int count_of_pilots = jtCountOfPilots.getSelectedIndex() + 1;
    for (ChannelControl chc : channelControls) {
      if (chc.index <= count_of_pilots) {
        chc.label.setVisible(true);
        chc.box.setVisible(true);
      } else {
        chc.label.setVisible(false);
        chc.box.setVisible(false);
      }
    }
  }//GEN-LAST:event_jtCountOfPilotsPropertyChange

  private void jcbStageTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStageTypeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jcbStageTypeActionPerformed

  private void butRecrateGropusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRecrateGropusActionPerformed
    // TODO add your handling code here:    
    try {
      if (stage != null && stage.ID != -1) {
        stage.IS_GROUP_CREATED = 0;
        VS_STAGE.dbControl.update(mainForm.con, stage);
        mainForm.setActiveRace(mainForm.activeRace);
        bSaveActionPerformed(evt);
        setVisible(false);
      }
    } catch (Exception e) {
      mainForm.toLog(e);
    }
  }//GEN-LAST:event_butRecrateGropusActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(StageNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(StageNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(StageNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(StageNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new StageNewForm(null).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Caption;
  private javax.swing.JButton bCancel;
  private javax.swing.JButton bSave;
  private javax.swing.JButton butRecrateGropus;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JComboBox jcbChannel1;
  private javax.swing.JComboBox jcbChannel2;
  private javax.swing.JComboBox jcbChannel3;
  private javax.swing.JComboBox jcbChannel4;
  private javax.swing.JComboBox jcbChannel5;
  private javax.swing.JComboBox jcbChannel6;
  private javax.swing.JComboBox jcbChannel7;
  private javax.swing.JComboBox jcbChannel8;
  private javax.swing.JComboBox jcbStageType;
  private javax.swing.JCheckBox jchGroupByPilotType;
  private javax.swing.JLabel jlChannel1;
  private javax.swing.JLabel jlChannel2;
  private javax.swing.JLabel jlChannel3;
  private javax.swing.JLabel jlChannel4;
  private javax.swing.JLabel jlChannel5;
  private javax.swing.JLabel jlChannel6;
  private javax.swing.JLabel jlChannel7;
  private javax.swing.JLabel jlChannel8;
  private javax.swing.JTextField jtCaption;
  private javax.swing.JComboBox jtCountOfPilots;
  private javax.swing.JTextField jtLapsCount;
  private javax.swing.JTextField jtMinLapTime;
  private javax.swing.JComboBox<String> parentStage;
  // End of variables declaration//GEN-END:variables
}
